### ISSUE TITLE
Livereload reloads whole page even if only the css has changed

### ISSUE THREAD

**Issue by josepjaume** [rwjblue/ember-cli-inject-live-reload#11]
I guess this has more to do with `ember-cli` (or even `broccoli`) but it impacts the effectiveness of `live-reload`.

When changing the css, and only the css, livereload signals the whole page to reload, since `ember-cli` will recompile the whole app and dump it on the `dist` folder again.

Do you know if there's any plans to support partial recompiling, so we can get the best of `livereload`? Reloading CSS only is a pleasure when it comes to style difficult-to-reach scenarios.

Thanks!

**Comment by lukemelia** [comment]
I think this issue can be closed.

**Comment by rwjblue** [comment]
Thanks @lukemelia !
