### ISSUE TITLE
live-reload does not work if rootURL is a subdirectory

### ISSUE THREAD

**Issue by cigoe** [rwjblue/ember-cli-inject-live-reload#15]
By default this plugin expects the ember projects to be served from the local hosts webroot. If you are serving it from a sub directory i.e http://localhost.site/app/ the ember-cli-live-reload.js script will 404.

I am able to get it to load locally if I modify index.js on line 10 and remove the forward slash  changing:

```
return '<script src="/ember-cli-live-reload.js" type="text/javascript"></script>';
```

into

```
return '<script src="ember-cli-live-reload.js" type="text/javascript"></script>';
```

I would assume we need to pull in the rootUrl from either ember or the ember-cli environment file if it is defined.

**Comment by pixelhandler** [comment]
I ran into this bug, I have custom baseURL in config/environment.js so yeah the script added for ember-cli-live-reload.js should use the ENV.baseURL ?

**Comment by rwjblue** [comment]
Discussed a gameplan with @pixelhandler in IRC.  Dumping the conversation for others to follow along:

```
18:56:59 <pixelhandler> rwjblue any thoughts on how to fix https://github.com/rwjblue/ember-cli-inject-live-reload/issues/15 ? I’d like to try but not sure how to get the ENV.baseURL from the app
19:04:21 <rwjblue> pixelhandler: ya, just a sec
19:05:24 <rwjblue> pixelhandler: so we do this in ember-cli in exactly the same hook as you need to do in ember-cli-inject-live-reload
19:05:26 <rwjblue> pixelhandler: https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/server/middleware/history-support/index.js#L18
19:05:54 <pixelhandler> sweet thx :)
19:06:06 <rwjblue> pixelhandler: so basically at https://github.com/rwjblue/ember-cli-inject-live-reload/blob/master/index.js#L35
19:06:29 <rwjblue> pixelhandler: you would do `options.baseUrl + '/ember-cli-live-reload.js'` instead of `'/ember-cli-live-reload.js'`
19:06:53 <pixelhandler> ok I’ll take a stab at #15
```

**Comment by pixelhandler** [comment]
Per @rwjblue via IRC...

Do this in ember-cli in exactly the same hook as you need to do in ember-cli-inject-live-reload

https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/server/middleware/history-support/index.js#L18

so basically at https://github.com/rwjblue/ember-cli-inject-live-reload/blob/master/index.js#L35
you would do `options.baseUrl + '/ember-cli-live-reload.js'` instead of `'/ember-cli-live-reload.js'`

**Comment by rwjblue** [comment]
@pixelhandler  :smiley:

**Comment by john-kurkowski** [comment]
As with #13, a workaround is to downgrade to ember-cli-inject-live-reload 1.2.3.

**Comment by pixelhandler** [comment]
@rwjblue I tried the addition of the baseURL like so: https://github.com/pixelhandler/ember-cli-inject-live-reload/compare/baseurl but that didn't work even with the baseURL inserted into the script the response was a 404. However when using v1.2.3 `http://localhost:35729/livereload.js?snipver=1` is used and works.

**Comment by pixelhandler** [comment]
@rwjblue @john-kurkowski Well looks like that branch works :) https://github.com/pixelhandler/ember-cli-inject-live-reload/compare/baseurl I'll create a pull request.

There is a gotcha though, using a custom url for your app (with the baseURL) your server may need to forward the /path_to_ember_app/ember-cli-live-reload.js request to :4200/path_to_ember_app/ember-cli-live-reload.js especially if you are using a different port to serve up the custom path.

Using nginx that may look like...

```
upstream brocolli_dev {
  server 127.0.0.1:4200;
  keepalive 64;
}

location ~ /*/ember-cli-live-reload.js {
    proxy_set_header  Host "localhost:4200";
    ... any other settings you need
    proxy_pass http://brocolli_dev;
}
```

**Comment by neilyoung** [comment]
Any progress on this?
